//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubEnrollment
    {
        public int ClubId { get; set; }
        public string UserId { get; set; }
        public bool IsLeader { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual User User { get; set; }
    }
}
