//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubSchedule
    {
        public int ClubId { get; set; }
        public int TimeSlotId { get; set; }
        public string DayValue { get; set; }
        public int SchoolYearId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Day Day { get; set; }
    }
}
