//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public Day()
        {
            this.ClubSchedules = new HashSet<ClubSchedule>();
            this.SectionSchedules = new HashSet<SectionSchedule>();
        }
    
        public string DayValue { get; set; }
    
        public virtual ICollection<ClubSchedule> ClubSchedules { get; set; }
        public virtual ICollection<SectionSchedule> SectionSchedules { get; set; }
    }
}
