//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestNews
    {
        public int LatestNewsId { get; set; }
        public int SchoolId { get; set; }
        public string Content { get; set; }
        public string UserId { get; set; }
        public System.DateTime PostedAt { get; set; }
    
        public virtual School School { get; set; }
        public virtual User User { get; set; }
    }
}
