//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkingPeriod
    {
        public MarkingPeriod()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.SectionSchedules = new HashSet<SectionSchedule>();
            this.TeacherSchedules = new HashSet<TeacherSchedule>();
        }
    
        public int MarkingPeriodId { get; set; }
        public int SchoolYearId { get; set; }
        public string Period { get; set; }
        public bool FullYear { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        public virtual ICollection<SectionSchedule> SectionSchedules { get; set; }
        public virtual ICollection<TeacherSchedule> TeacherSchedules { get; set; }
    }
}
