//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolYear
    {
        public SchoolYear()
        {
            this.ClubSchedules = new HashSet<ClubSchedule>();
            this.MarkingPeriods = new HashSet<MarkingPeriod>();
            this.SectionSchedules = new HashSet<SectionSchedule>();
        }
    
        public int SchoolYearId { get; set; }
        public int SchoolId { get; set; }
        public string Year { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<ClubSchedule> ClubSchedules { get; set; }
        public virtual ICollection<MarkingPeriod> MarkingPeriods { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<SectionSchedule> SectionSchedules { get; set; }
    }
}
