//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolYear
    {
        public SchoolYear()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.TeacherSchedules = new HashSet<TeacherSchedule>();
        }
    
        public string Year { get; set; }
        public int SchoolId { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<TeacherSchedule> TeacherSchedules { get; set; }
    }
}
