//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionSchedule
    {
        public int SectionId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public int SchoolId { get; set; }
        public int TimeSlotId { get; set; }
        public string DayValue { get; set; }
        public int MarkingPeriodId { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual MarkingPeriod MarkingPeriod { get; set; }
        public virtual Section Section { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
