//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.SectionSchedules = new HashSet<SectionSchedule>();
            this.TeacherSchedules = new HashSet<TeacherSchedule>();
            this.Threads = new HashSet<Thread>();
        }
    
        public int SectionId { get; set; }
        public string SectionName { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public int SchoolId { get; set; }
        public string Description { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<SectionSchedule> SectionSchedules { get; set; }
        public virtual ICollection<TeacherSchedule> TeacherSchedules { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
