//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ClubEnrollments = new HashSet<ClubEnrollment>();
            this.LatestNews = new HashSet<LatestNews>();
            this.PrivateMessages = new HashSet<PrivateMessage>();
            this.PrivateMessages1 = new HashSet<PrivateMessage>();
            this.Threads = new HashSet<Thread>();
            this.Schools = new HashSet<School>();
        }
    
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string GenderType { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastLoggedIn { get; set; }
        public Nullable<System.DateTime> LastLoggedOut { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<ClubEnrollment> ClubEnrollments { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<LatestNews> LatestNews { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessages1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
        public virtual UserCredential UserCredential { get; set; }
        public virtual ICollection<School> Schools { get; set; }
    }
}
